knowledge_base:
  csv_paths:
    - /home/sachin/Music/NFL/Kaggle_Data/team_stats_2003_2023.csv
    - /home/sachin/Music/NFL/Kaggle_Data/nfl_combine_2010_to_2023.csv
    - /home/sachin/Music/NFL/Kaggle_Data/ThrowbackDataThursday 2019 Week 1 - NFL Injuries 2012 to 2017.csv

  json_paths:
    - /home/sachin/Music/NFL/SportsRadar_API/season_schedule/2023/season_schedule_2023_REG.json
    - /home/sachin/Music/NFL/SportsRadar_API/nfl_injuries/2023/nfl_injuries_2023_REG_week1.json
    - /home/sachin/Music/NFL/SportsRadar_API/season_standing/2023/season_standings_2023_REG.json

db: 
  chroma_db_path: db

nfl_websites:
  nfl: https://www.nfl.com/international/
  espn: https://www.espn.com/nfl/
  nfl_news: https://www.nfl.com/news/
  cbs: https://www.cbssports.com/nfl/#:~:text=NFL%20Football%20%2D%20News%2C%20Scores%2C,National%20Football%20League%20%2D%20CBSSports.com
  pfr: https://www.pro-football-reference.com/
  



