data_embedding_task:
  description: >
    Gather and preprocess data from various sources.
  expected_output: >
    Database containing all the embedded data from the CSV an JSON file present in config
  agent: data_embedding_agent

data_retrieval_task:
  description: >
    Retrieve the documents from the database
  expected_output: >
    List of all the relevant documents related to user prompt from ChromaDB 
  agent: data_retrieval_agent

# statistical_analysis_task:
#   description: >
#     Compute basic statistical metrics from processed data.
#   expected_output: >
#     Statistical summaries including mean, median, variance, etc.
#   agent: statistical_analysis_agent

# contextual_analysis_task:
#   description: >
#     Analyze data in the context of game-specific factors.
#   expected_output: >
#     Contextual insights tailored to the game's nuances.
#   agent: contextual_analysis_agent

# matchup_analysis_task:
#   description: >
#     Assess key matchups based on processed data.
#   expected_output: >
#     Detailed comparison of critical matchups.
#   agent: matchup_analysis_agent

# historical_performance_task:
#   description: >
#     Provide historical performance context for the data.
#   expected_output: >
#     Historical trends and insights relevant to current analysis.
#   agent: historical_performance_agent

# expert_knowledge_task:
#   description: >
#     Integrate domain expertise into the analysis.
#   expected_output: >
#     Insights and recommendations based on expert domain knowledge.
#   agent: expert_knowledge_agent

# machine_learning_task:
#   description: >
#     Generate predictions using trained machine learning models.
#   expected_output: >
#     Predictive results with confidence intervals.
#   agent: machine_learning_agent

# consensus_prediction_task:
#   description: >
#     Combine outputs from all agents for the final prediction.
#   expected_output: >
#     A cohesive final prediction integrating all insights.
#   agent: consensus_agent

consensus_prediction_task:
  description: >
    Derive insights from output of data_retrieval_agent
  expected_output: >
    A detailed summary of the document retrieved in the output of data_retrieval_agent
  agent: consensus_agent